# -*- coding: utf-8 -*-
"""student_management_system version 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g60Lwfqk3mn9777Q3jOw4EL9wpL7IDPC
"""

#jason module
import json

#student list!
students = []

#Load Students/ a module for loading / reading of files from python
def json_load_student():
  global students
  try:
    with open("students.json", "r") as file:
      students = json.load(file)
  except FileNotFoundError:
    students = []

#save students
def save_students():
  with open("students.json", "w") as file:
    json.dump(students, file, indent=4)


#age validation
def validate_age ():
  while True:
    try:
      #validate age inputs
      age = int(input("Enter Student age: "))
      if age <= 0:
        print("Invalid age. Age must be greater than 0!")
      elif age >= 120:
        print("Invalid age. Age must be between 1 and 120.")
      else:
        return age
    except ValueError:
      print("Invalid input. please enter only numbers.")


#name validation
def validate_name ():
  while True:
    name = input("Enter student name: ").strip()
    if name == "":
      print("Name can not be empty!.")
    elif name in ['0','1','2','3','4','5','6','7','8','9']:
      print("Invalid input. Name cannot be a number.")
    else:
      return name

#student helper function
def find_student_by_id(student_id):
  for student in students:
    if student["student_id"] == student_id:
      return student
  return None

#gender validation
def validate_gender():
  while True:
    gender = input("Enter student gender: ").strip().lower()
    if gender in ["male", "female", "other"]:
      return gender
    else:
      print("Invalid gender. Please enter ('male', 'female', or 'other').")


#department validation
def validate_department():
  while True:
    department = input("Enter student department: ").strip()
    if department == "":
      print("department can not be empty!.")
    elif department in ['0','1','2','3','4','5','6','7','8','9']:
      print("Invalid input. department cannot be a number.")
    else:
      return department


#student id validation
def validate_student_id():
  while True:
    new_student_id = input("Enter student ID: ").strip().upper()
    if new_student_id == "":
      print("Student ID cannot be empty.")
      continue
    duplicate = False
    for student in students:
      student_id = student["student_id"]
      if new_student_id == student_id:
        print("Student ID already exists. Please enter a different ID.")
        duplicate = True
        break
    if not duplicate:
      return new_student_id


#Student registration
def register_student():
  print("Register Student!")
  print("Enter your Details")
  student_id = validate_student_id()
  name = validate_name()
  age = validate_age()
  gender = validate_gender()
  department = validate_department()
  student = {
    "student_id": student_id,
    "name": name,
    "age": age,
    "gender": gender,
    "department": department
  }
  students.append(student)
  print("\nStudent registered successfully!\n")
  save_students()



#View Student
def view_students():
  if len(students) == 0:
    print("No students found.")
  else:
    print("List of students:")
    for student in students:
      print(f"ID: {student['student_id']}")
      print(f"Name: {student['name']}")
      print(f"Age: {student['age']}")
      print(f"Gender: {student['gender']}")
      print(f"Department: {student['department']}")
      print("-" * 40)



#Search Students
def search_student():
  get_student_id = input("Enter Student Id: ").strip().upper()
  student = find_student_by_id(get_student_id)
  if student:
    print("\nStudent Found:")
    print(f"ID: {student['student_id']}")
    print(f"Name: {student['name']}")
    print(f"Age: {student['age']}")
    print(f"Gender: {student['gender']}")
    print(f"Department: {student['department']}")
  else:
    print("\nStudent not found.")



#update student
def update_student():
  print("Update Profile!")
  print("========================================")
  print("Enter your Details")
  get_student_id = input("Enter Student Id: ").strip().upper()
  student = find_student_by_id(get_student_id)
  if student:
    student["name"] = validate_name()
    student["age"] = validate_age()
    student["gender"] = validate_gender()
    student["department"] = validate_department()
    print("\nStudent updated successfully!")
  else:
    print("\nStudent not found.")
  save_students()


#delete Student
def delete_student():
  print("Delete Profile!")
  print("========================================")
  print("Enter your Details")
  get_student_id = input("Enter Student Id: ").strip().upper()
  student = find_student_by_id(get_student_id)
  if student:
    students.remove(student)
    print("\nStudent deleted successfully!")
  else:
    print("\nStudent not found.")
  save_students()




#Starting the App!\
print("Welcome!")
print("==========Student Management System=============")
json_load_student()
while True:
  print("=================================================")
  print("Please SELECT an Option from (1 - 6) ")
  print("1. Add New Student")
  print("2. View Students")
  print("3. Search Student")
  print("4. Edit Student")
  print("5. Delete Student")
  print("6. Quit")
  print("=================================================")
  choice = input("Enter your choice: ")
  if choice == "1":
    print("Please carefully enter your details below!")
    print("=================================================")
    register_student()
  elif choice == "2":
    print("View Your Student")
    view_students()
  elif choice == "3":
    print("Search Student")
    search_student()
  elif choice == "4":
    print("Update Student")
    update_student()
  elif choice == "5":
    print("Delete Student")
    delete_student()
  elif choice == "6":
    print("Thank you for using the Student Management System.")
    break
  else:
    print("Invalid Choice")



